pipeline {
    agent any
    
    stages {
        stage('Compilação') {
            steps {
                sh 'mvn clean package'
            }
        }
        
        stage('Teste') {
            steps {
                sh 'mvn test'
            }
        }
        
        stage('Implantação no Kubernetes') {
            environment {
                KUBECONFIG = credentials('kubernetes-credentials-id')
            }
            steps {
                script {
                    withCredentials([file(credentialsId: 'kubernetes-credentials-id', variable: 'KUBECONFIG')]) {
                        sh 'kubectl apply -f kubernetes/deployment.yaml --kubeconfig=$KUBECONFIG'
                    }
                }
            }
        }
    }
}
